# Generated by Django 5.2.8 on 2025-11-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.DateTimeField(),
        ),
    ]
